sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - wget https://neo4j.com/artifact.php?name=neo4j-community-3.2.0-unix.tar.gz
  - tar -xzf artifact.php?name=neo4j-community-3.2.0-unix.tar.gz
  - sudo chmod a+w neo4j-community-3.2.0/conf/neo4j.conf
  - echo "dbms.connectors.default_listen_address=0.0.0.0" >> neo4j-community-3.2.0/conf/neo4j.conf
  - echo "browser.remote_content_hostname_whitelist=*" >> neo4j-community-3.2.0/conf/neo4j.conf
  - sudo neo4j-community-3.2.0/bin/neo4j restart
  - sudo neo4j-community-3.2.0/bin/neo4j-admin set-initial-password test
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true